# Page settings
baseurl = "localhost:1313"
title = "The Esanjo Way"
languageCode = "en-us"
theme = "hugo-esanjo"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  disableSearch = true
  custom_css = ["/css/custom_1.css"]
  editURL = "https://github.com/Esanjo/esanjo-way/edit/master/content/"
  ordersectionsby = "weight"
  pluralizeListTitles = false

  # Meta
  author = "The Esanjo Team"
  description = "How we work at Esanjo"
  email = ""
  # Navigation
  [params.navigation]
    brand = "Esanjo"
    home = "Home"
    work = "Projects"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    team = "Team"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
     url = "/"
     name = "The Esanjo Way"
     weight = 10

  # Hero section
  [params.hero]
    title = "The Esanjo Way"
    subtitle = 'How we work at Esanjo'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"


  # Contact section
  [params.contact]
    enable = false
    map = true
    title = "Get in touch"
    description = "Get in touch with us by filling this simple form"

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = 'with <i class="icon-heart2"></i></a> at Esanjo'
