# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Esanjo Hugo"
license = "MIT"
licenselink = "https://github.com/Esanjo/esanjo-way/blob/master/LICENSE.md"
description = "Esanjo Hugo, built on the Elate theme ported to Hugo by Pieter Saey"
homepage = "https://way.esanjo.com"
tags = ["Esanjo", "Hugo", ]
features = ["", "", ""]

[author]
  name = "Jackson Achankunju, Esanjo Ltd"
  homepage = "https://way.esanjo.com"

[original]
  name = "Elate Hugo"
  homepage = "https://github.com/saey55/hugo-elate-theme/"
  license = "MIT"
  licenselink = "https://github.com/saey55/hugo-elate-theme/blob/master/LICENSE.md"
